# Generated by Django 3.2.18 on 2023-07-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('staff', 'Staff'), ('vendor', 'Vendor')], default='staff', max_length=50, null=True),
        ),
    ]
