# Generated by Django 3.2.18 on 2023-07-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matric_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Matric number'),
        ),
    ]
