# Generated by Django 3.2.18 on 2023-10-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20231020_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='missing',
            field=models.BooleanField(default=False),
        ),
    ]
