# Generated by Django 3.2.18 on 2023-10-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_uploadedtemplates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matric number / Staff ID'),
        ),
    ]
