# Generated by Django 3.2.18 on 2023-11-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customuser_is_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_logged_in',
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
